
import java.awt.event.ActionListener;
import java.awt.event.MouseAdapter;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author NANON
 */
public class GUI extends javax.swing.JPanel {

    /**
     * Creates new form viewGUI
     */
    public GUI() {
        initComponents();
    }
    
    public Object getBtnProcess() {
        return jButtonProcess;
    }
    
    public Object getBtnReset() {
        return jButtonReset;
    }
    
    public JTable getTableLexic() {
        return jTableLexic;
    }
    
    public void setTotalLexicToken(String s) {
        jTextFieldTotalLexic.setText(s);
    }
    
    public String getInputString() {
        return jTextFieldString.getText();
    }
    
    public void reset() {
        jTextFieldString.setText("Type here ... ... ...");
        jTextFieldTotalLexic.setText("");
        DefaultTableModel model = (DefaultTableModel) jTableLexic.getModel();
        model.setRowCount(0);
    }
    
    public void addListener(ActionListener e) {
        jButtonReset.addActionListener(e);
        jButtonProcess.addActionListener(e);
    }
    
    public void addAdapter(MouseAdapter e) {
        jTextFieldString.addMouseListener(e);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelTittle = new javax.swing.JLabel();
        jLabelCaptionTittle = new javax.swing.JLabel();
        jTextFieldString = new javax.swing.JTextField();
        jButtonReset = new javax.swing.JButton();
        jButtonProcess = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldTotalLexic = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableLexic = new javax.swing.JTable();

        setBackground(new java.awt.Color(255, 255, 255));

        jLabelTittle.setBackground(new java.awt.Color(255, 255, 255));
        jLabelTittle.setFont(new java.awt.Font("Open Sans Condensed", 0, 36)); // NOI18N
        jLabelTittle.setForeground(new java.awt.Color(0, 102, 204));
        jLabelTittle.setText("LEXICAL ANALYZER");

        jLabelCaptionTittle.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabelCaptionTittle.setText("K E L O M P O K   T B A");

        jTextFieldString.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jTextFieldString.setText("Type here ... ... ...");

        jButtonReset.setFont(new java.awt.Font("Open Sans Condensed", 0, 12)); // NOI18N
        jButtonReset.setText("Reset");

        jButtonProcess.setFont(new java.awt.Font("Open Sans Condensed", 0, 12)); // NOI18N
        jButtonProcess.setText("Process");

        jLabel1.setFont(new java.awt.Font("Calibri Light", 0, 12)); // NOI18N
        jLabel1.setText("Total Lexic Token :");

        jTextFieldTotalLexic.setEditable(false);
        jTextFieldTotalLexic.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N

        jTableLexic.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N
        jTableLexic.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "String", "Type", "Lexic Token"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableLexic.setRowHeight(20);
        jScrollPane1.setViewportView(jTableLexic);

        jScrollPane2.setViewportView(jScrollPane1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldString)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldTotalLexic, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonProcess, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonReset, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabelTittle)
                .addGap(120, 120, 120))
            .addGroup(layout.createSequentialGroup()
                .addGap(185, 185, 185)
                .addComponent(jLabelCaptionTittle)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 480, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelTittle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelCaptionTittle)
                .addGap(18, 18, 18)
                .addComponent(jTextFieldString, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonReset, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonProcess, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jTextFieldTotalLexic, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 203, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonProcess;
    private javax.swing.JButton jButtonReset;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelCaptionTittle;
    private javax.swing.JLabel jLabelTittle;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableLexic;
    private javax.swing.JTextField jTextFieldString;
    private javax.swing.JTextField jTextFieldTotalLexic;
    // End of variables declaration//GEN-END:variables
}
